//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

#ifndef CUSTOM_LOGO
#define LOGO_WIDTH   1
#define LOGO_HEIGHT  1

const unsigned char logo[] PROGMEM = { //AVR-GCC, WinAVR
0x00
};
#else
LOGO_BITMAP
#endif
